### ISSUE TITLE
`no-yield-only` todo is not removed after fixing in addon

### ISSUE THREAD

**Issue by locks** [ember-template-lint/ember-template-lint#1887] opened 2021-04-07 11:55 UTC
I am using ember-template-lint in an addon and I tried to fix a `no-yield-only` todo item by removing the template file and any `layout` imports in the component JavaScript.

However, when I run `--update-todo`, the todo is not removed as expected.

I have tried to delete `.lint-todo` and recreate the todo list, I thought maybe it was a false positive, but it did not make a difference.

**Comment by MelSumner** [comment] 2021-04-13 21:15
The correct command to run to remove a todo is `--fix`. So if you are using the default command in Ember apps, it would be `yarn lint:hbs --fix.`

**Comment by locks** [comment] 2021-04-14 12:02
That is troublesome for this particular application, as running `--fix` makes additional changes that are making the test suite fail to pass.
It is also confusing to me as a developer because fixing other links (like `no-implicit-this`) and running `--update-todo` does remove the resolved todo file.

**Comment by locks** [comment] 2021-04-14 12:04
Follow up, I tried running `--fix` and the resolved `no-yield-only` todo files were not removed.

**Comment by MelSumner** [comment] 2021-04-14 14:06
> Follow up, I tried running `--fix` and the resolved `no-yield-only` todo files were not removed.

Here's what should happen according to the documentation: https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/todos.md#usage

**Comment by MelSumner** [comment] 2021-04-14 14:07
> That is troublesome for this particular application, as running `--fix` makes additional changes that are making the test suite fail to pass.

I definitely think you should weigh in on Issue #1852 then :)

**Comment by rwjblue** [comment] 2021-04-14 15:22
> That is troublesome for this particular application, as running --fix makes additional changes that are making the test suite fail to pass.

Please file a bug report, `--fix` should **always** be safe. If it isn't there is a bug, that should be fixed.

**Comment by scalvert** [comment] 2021-04-14 20:25
@locks a reproduction would be very helpful here. 

I could imagine this is a problem since we operate against the discovered violations in the project, and manipulate the todo files accordingly. If that file path is not longer present in the violation results, we may skip it and subsequently orphan the todo file.

It should be fairly easy to test this.

**Comment by MelSumner** [comment] 2021-04-26 21:15
I'm closing this because I can't reproduce it. Please re-open if you can repro.

**Closed by MelSumner** 2021-04-26 21:15 UTC
Labels: todos
