### ISSUE TITLE
Attribute Order Breaks For Link Components

### ISSUE THREAD

**Issue by Alonski** [ember-template-lint/ember-template-lint#2710] opened 2022-11-17 18:37 UTC
Not sure why but Attribute Order breaks when using `<Link>` component:
Input:
```hbs
<Link
  @b="taco"
  @a={{a}}
>
  {{taco}}
</Link>
```
Output after ETL Fix:
```handlebars
<Link @a={{a}} @b="taco">
  {{taco}}
```
Notice the missing closing `</Link>` tag

**Comment by Alonski** [comment] 2022-11-17 18:37
CC @rob-long If you want to take a look
Thanks for doing this work BTW so awesome!

**Comment by bertdeblock** [comment] 2022-11-19 11:21
My guess would be that the issue is more about the component having the same name as a void tag.
For example, the same happens if you use `Meta` as the component's name.

**Comment by bertdeblock** [comment] 2022-11-19 11:25
I think we need this fix to be released in the VM: https://github.com/glimmerjs/glimmer-vm/pull/1390.

**Comment by bertdeblock** [comment] 2023-03-24 18:17
FYI, there's a [new release](https://github.com/glimmerjs/glimmer-vm/releases/tag/v0.84.3), so we should be able to fix this issue.

**Closed** 2023-03-28 17:53 UTC
Labels: bug
