### ISSUE TITLE
Make it possible to indent block params the same as the other attributes

### ISSUE THREAD

**Issue by Windvis** [ember-template-lint/ember-template-lint#546] opened 2018-10-17 12:09 UTC
I prefer that block params start with the same indentation as the other block attributes:
```
{{#employee-details
  firstName=firstName
  lastName=lastName
  age=age
  avatarUrl=avatarUrl
  as |employee|
}}
  {{employee.fullName}}
{{/employee-details}}
```

Is this configurable? I couldn't find it on the [attribute-indentation page](https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/attribute-indentation.md).

I get the following error: `Incorrect indentation of block params 'as |employee|
}}' beginning at L33:C2. Expecting the block params to be at L33:C0.`

Thanks!

**Comment by jelhan** [comment] 2018-12-09 21:31
Duplicate of #554 (or the other way around, as you prefer :laughing:)

**Closed** 2021-02-19 18:52 UTC
