### ISSUE TITLE
Satisfying "argument-less-helper-paren-less-invocation" added in Ember 3.27 results in parse errors

### ISSUE THREAD

**Issue by randallmorey** [ember-template-lint/ember-template-lint#2163] opened 2021-11-02 19:44 UTC
[A deprecation `argument-less-helper-paren-less-invocation` was introduced in Ember 3.27](https://deprecations.emberjs.com/v3.x/#toc_argument-less-helper-paren-less-invocation) where a helper implicitly invoked for a named argument:

```hbs
<SomeComponent @arg={{someHelper}} />
```

should be invoked explicitly using parens:

```hbs
<SomeComponent @arg={{(someHelper)}} />
```

However, the new explicit invocation syntax is not understood by `ember-template-lint` and results in a parse error.  For example:

```sh
$ ember-template-lint .
app/templates/application.hbs
  -:-  error  Parse error on line 7:
...='test-app' @text={{(someHelper)}} />
-----------------------^
Expecting 'ID', 'STRING', 'NUMBER', 'BOOLEAN', 'UNDEFINED', 'NULL', 'DATA', got 'OPEN_SEXPR'  undefined
```

**Comment by bertdeblock** [comment] 2021-11-02 19:49
Duplicate of #1963.

**Comment by bertdeblock** [comment] 2022-04-10 18:05
https://github.com/ember-template-lint/ember-template-lint/pull/2172 should have resolved this issue, so I think we can close this?

**Comment by bertdeblock** [comment] 2022-04-13 17:32
Closing since this was a duplicate of #1963, which was also resolved in `ember-template-lint` v4.

**Closed by bertdeblock** 2022-04-13 17:32 UTC
Labels: bug
