### ISSUE TITLE
My .template-lintrc.js is being ignored

### ISSUE THREAD

**Issue by Redsandro** [ember-template-lint/ember-template-lint#669] opened 2019-03-09 00:06 UTC
I'm trying to stop Ember from complaining about single quotes in templates.

```
'use strict'

module.exports = {
	extends: 'recommended',
	rules: {
		'block-indentation': 'tab',
		'quotes': 'single'
	},
	ignore: [
		'app/templates/test.hbs',
		'app/templates/*',
		'testapp/app/templates/*',
		'testapp/templates/*'
	]
}
```

Nothing changes.

It must be something I did. I don't install things globally because of reasons, so I start my app like this:

```
 env DEBUG=ember-cli-fastboot:* ./node_modules/ember-cli/bin/ember s
```

Versions:

```
  "devDependencies": {
    "@ember/jquery": "^0.5.2",
    "@ember/optional-features": "^0.6.3",
    "@fortawesome/ember-fontawesome": "^0.1.13",
    "@fortawesome/free-regular-svg-icons": "^5.7.0",
    "@fortawesome/free-solid-svg-icons": "^5.7.2",
    "bootstrap": "^4.3.1",
    "broccoli-asset-rev": "^2.7.0",
    "ember-ajax": "^3.1.0",
    "ember-auto-import": "^1.2.21",
    "ember-bootstrap": "^2.5.0",
    "ember-cli": "~3.7.1",
    "ember-cli-analytics": "^1.4.1",
    "ember-cli-app-version": "^3.2.0",
    "ember-cli-babel": "^7.1.2",
    "ember-cli-dependency-checker": "^3.0.0",
    "ember-cli-eslint": "^4.2.3",
    "ember-cli-fastboot": "^2.0.4",
    "ember-cli-htmlbars": "^3.0.0",
    "ember-cli-htmlbars-inline-precompile": "^1.0.3",
    "ember-cli-inject-live-reload": "^1.8.2",
    "ember-cli-moment-shim": "^3.7.1",
    "ember-cli-sass": "^10.0.0",
    "ember-cli-sri": "^2.1.1",
    "ember-cli-template-lint": "^1.0.0-beta.1",
    "ember-cli-uglify": "^2.1.0",
    "ember-data": "~3.7.0",
    "ember-export-application-global": "^2.0.0",
    "ember-load-initializers": "^1.1.0",
    "ember-maybe-import-regenerator": "^0.1.6",
    "ember-moment": "^7.8.1",
    "ember-qunit": "^3.4.1",
    "ember-resolver": "^5.0.1",
    "ember-source": "~3.7.0",
    "ember-truth-helpers": "^2.1.0",
    "ember-welcome-page": "^3.2.0",
    "eslint-plugin-ember": "^5.2.0",
    "howler": "^2.1.1",
    "loader.js": "^4.7.0",
    "qunit-dom": "^0.8.0",
    "sass": "^1.17.2"
  },
```

Errors:

```
testapp/templates/components/search-form.hbs
  1:12  error  you must use single quotes in templates  quotes
  7:8  error  you must use single quotes in templates  quotes
  8:15  error  you must use single quotes in templates  quotes
  9:14  error  you must use single quotes in templates  quotes
  10:7  error  you must use single quotes in templates  quotes
  11:13  error  you must use single quotes in templates  quotes
  13:15  error  you must use single quotes in templates  quotes
  13:53  error  you must use single quotes in templates  quotes
  17:13  error  you must use single quotes in templates  quotes
  17:34  error  you must use single quotes in templates  quotes
  18:13  error  you must use single quotes in templates  quotes
  18:32  error  you must use single quotes in templates  quotes
  21:12  error  you must use single quotes in templates  quotes
  24:15  error  you must use single quotes in templates  quotes
  27:20  error  you must use single quotes in templates  quotes
```
etc.

**Comment by kjarri** [comment] 2019-04-05 13:36
As far as I can tell, this is working as intended. the quotes rule accepts either `'double'` or `'single'`. You've set it to single and therefore the linter complains about any double quotes it finds in your templates.

**Comment by Redsandro** [comment] 2019-04-05 14:19
I guess it might be mild dyslexia or a poorly written issue.
Let me revisit this issue when I'm working on the project that caused this again.

**Comment by Turbo87** [comment] 2019-11-30 12:29
@Redsandro is this still an issue? seems to work without issues for me 🤔

**Comment by Turbo87** [comment] 2019-12-13 09:10
I'll close the issue for now. if this is still an issue please let us know.

**Closed by Turbo87** 2019-12-13 09:10 UTC
