### ISSUE TITLE
Question: Lint a workspace in VSCode?

### ISSUE THREAD

**Issue by edeis53** [ember-template-lint/ember-template-lint#813] opened 2019-08-28 21:37 UTC
When using VSCode workspace with multiple folders/apps, template linting doesn't run, however the .js files are linted properly.
eg.
```
My Workspace
     frontend-ember-app
     backend-ember-app
```
     
I've tried configuring the VSCode eslint extension to lint the entire workspace, the eslint server seems to pickup the config, but template linting doesn't run for the .hbs files.

What additional config is required?
```
  "settings": {
    "eslint.autoFixOnSave": true,
    "eslint.workingDirectories": [
      {
        "directory": "/Users/Me/FrontEndApp",
        "changeProcessCWD": true
      },
            {
        "directory": "/Users/Me/BackEndApp",
        "changeProcessCWD": true
      }
    ],
    "eslint.lintTask.enable": true,
    "eslint.lintTask.options": "-c /Users/Me/FrontEndApp/.eslintrc.json --ignore-path /Users/Me/FrontEndApp/.eslintignore ."
  }
```

```
[Info  - 2:10:18 PM] ESLint server is running.
[Info  - 2:10:19 PM] ESLint library loaded from: /Users/Me/FrontEndApp/node_modules/eslint/lib/api.js
```

**Reproduction**
-Init two ember apps.
-Add both app folders to a workspace in VS code.
-Add an empty `<img />` to application.hbs

**Expected Result**
should get a line error within the VScode editor for the line `img tags must have an alt attribute : ember-template-lint` but it doesn't happen.

**Comment by rwjblue** [comment] 2019-08-28 23:28
Hmm, can you make a demo repo (along with the commands you expect should work, but don't) that I can use to test?

**Comment by edeis53** [comment] 2019-08-29 03:37
Thanks for your attention @rwjblue .

I have made a reproduction of the issue with step-by-step instructions in the README.md here:
https://github.com/edeis53/ember-vscode-templatelint-issue/blob/master/README.md

Let me know if you need any clarification.

**Comment by rwjblue** [comment] 2019-08-29 15:12
That reproduction is perfect, thank you!

I haven't stepped through the specific code here but I suspect that the issue is the way we discover the config file. Specifically, we look for configuration ([see here](https://github.com/ember-template-lint/ember-template-lint/blob/333e2eafa634669237c65c5b0ce7c9520bae58f1/lib/get-config.js#L21)) from the current working directory upwards, but in Scenario B (from the README you linked) we actually need to try to look from the _file location_ upwards. AFAICT, that is what ESLint is doing as well.

**Comment by edeis53** [comment] 2019-08-30 02:48
That's sounds like the right direction. I don't yet have any experience with programming linters or vscode extenions, but if there is any way I can assist, let me know.

**Comment by rwjblue** [comment] 2019-08-30 12:34
We can probably tweak that `getConfig` function I linked above to accept the filename to be used and attempt to `resolveUp` from that location instead of starting with `process.cwd()` (like we do now). We'd have to gracefully handle when a filename isn't known, or the filename we were given doesn't actually exist on disk (relative to `process.cwd()`) but that seems feasible. One thing I don't want, is to merge configs from all parent directories so we'd still stop resolving once we find the first match.

@edeis53 - I'm not sure when I'd have time to poke at this, but I'm very happy to help you through the process if you wanted to give it a shot. A great starting point would be to add a failing test case to [this set of tests](https://github.com/ember-template-lint/ember-template-lint/blob/master/test/unit/get-config-test.js), then we can work backwards into fixing...

**Comment by edeis53** [comment] 2019-08-30 16:25
IMHO this test seems like it might be providing coverage:
https://github.com/ember-template-lint/ember-template-lint/blob/1ebbb3820c13224917e3927ecad036d459199910/test/unit/get-config-test.js#L25

Because in addition to the reproduction, I also tried configuring `eslint.workingDirectories` setting in VSCode which sets process.cwd. `get-config.js` looks like it should grab `.template-lintrc` from the process.

> eslint.workingDirectories - an array for working directories to be used. ESLint resolves configuration files (e.g. eslintrc) relative to a working directory. This new settings allows users to control which working directory is used for which files (see also CLIEngine options#cwd). 

```
{
  "eslint.workingDirectories": [
    {
      "directory": "./app1",
      "changeProcessCWD": true
    },
    {
      "directory": "./app2",
      "changeProcessCWD": true
    }
  ]
}
```

It makes me wonder if there is also an issue with ember-language-server/vscode extension?? eg. https://github.com/emberwatch/ember-language-server/blob/f735699e363a3e1743a2984500dc3a91c488534d/src/template-linter.ts#L56

For example, I also installed ember-template-lint globally and it does lint both app1 and app2 when `ember-template-lint . ` is run from the parent folder. However, it doesn't catch the same lint errors and is missing `"img tags must have an alt attribute ember-template-lint"`
```
⋊> ~/N/N/ember-vscode-templatelint-issue on master ⨯ ember-template-lint .                                                                                            09:17:19
/Users/daisu/NANOCODE/NANOTONE/ember-vscode-templatelint-issue/app1/app/templates/application.hbs
  12:0  error  Self-closing a void element is redundant  self-closing-void-elements

/Users/daisu/NANOCODE/NANOTONE/ember-vscode-templatelint-issue/app2/app/templates/application.hbs
  12:0  error  Self-closing a void element is redundant  self-closing-void-elements

✖ 2 problems (2 errors, 0 warnings)
```

**Comment by edeis53** [comment] 2019-09-12 07:08
@rwjblue solved the issue.

I've installed "Unstable Ember Language Server" `lifeart.vscode-ember-unstable` VSCode extension and template linting works just fine in a workspace with multiple apps/folders.

**Comment by danwenzel** [comment] 2019-11-22 22:23
@edeis53 @rwjblue - Correct me if I'm wrong, but I believe this is still broken if you do not have a `.template-lintrc.js` file at the package level.  We have one only at the root of the monorepo, and vs code doesn't seem to be showing errors

**Comment by edeis53** [comment] 2019-11-22 22:52
I believe that's true. It's an issue with the Ember Language server extension for VScode, instead use the "Unstable Ember Language Server" from `lifeart.vscode-ember-unstable` extension instead. It's a fork and has a lot of improvements that from what I've heard will eventually be merged into the original Ember Langauge Server.

**Comment by danwenzel** [comment] 2019-11-22 22:54
@edeis53 - sorry, I wasn't clear:  Even when using the unstable ember language server, vs code template linting is not working when I only have a template-lintrc file at the root of the monorepo

**Comment by rwjblue** [comment] 2020-01-15 22:01
I'm not sure if this is or is not still an issue. I would definitely expect running `./node_modules/.bin/ember-template-lint **/*.hbs` from the monorepo root to work.

@danwenzel - Are you saying that is **not** working?

**Comment by rwjblue** [comment] 2020-02-21 01:16
AHA! That makes sense @danwenzel, thank you!  For now, the easiest solution is to add files in your subpackages that are effectively `module.exports = require('../../../.template-lintrc');`.

I think we should fix this (specifically, I've realized recently thanks to @krisselden that sometimes VSCode extensions always run from the current files directory and not the project root). The fix should be straight forward: use `find-up` from the `process.cwd()` to find the first `.template-lintrc.js` that we find.

**Comment by rwjblue** [comment] 2020-02-22 15:48
Fixed by https://github.com/ember-template-lint/ember-template-lint/pull/1138 (which will land in a 2.0.0 beta soon).

**Closed by rwjblue** 2020-02-22 15:48 UTC
Labels: bug, help wanted

**Comment by betocantu93** [comment] 2021-08-24 23:04
Not sure if I'm doing something wrong, but I'm having this same problem when using yarn workspaces, If I open one of the packages alone, I'll get lints on vscode, but it doesn't if I open the whole repo, like following the steps in this [repro](https://github.com/edeis53/ember-vscode-templatelint-issue/blob/master/README.md)
