### ISSUE TITLE
Unexpected {{partial}} usage

### ISSUE THREAD

**Issue by papakay** [ember-template-lint/ember-template-lint#493] opened 2018-09-07 06:53 UTC
Please i have a template lint error with the line of code below

```
{{partial "-sales-table-header"}}
```

Ember 3.4.1
Ember template lint 1.0.0.beta.1

**Comment by rwjblue** [comment] 2018-09-07 16:46
Agree with @jherdman here. The exact intent of this rule is to help guide folks to avoiding partial usage...

**Comment by rwjblue** [comment] 2018-09-07 16:46
Closing as not a bug (happy to reopen if I've miss-understood...)

**Closed by rwjblue** 2018-09-07 16:46 UTC

**Comment by papakay** [comment] 2018-09-07 17:39
@jherdman and @rwjblue Thanks for the insight and direction.
