### ISSUE TITLE
Colocating component hbs file prevents cleanup

### ISSUE THREAD

**Issue by tylerbecks** [ember-template-lint/ember-template-lint#2085] opened 2021-08-30 21:25 UTC
If I have the following hbs file:
`addon/templates/components/foo.hbs`
And I move it to:
`addon/components/foo.hbs`

The TODOs for that file should be cleaned up or moved/updated, but the `--clean-todo` flag doesn't catch this.

**Comment by scalvert** [comment] 2021-08-30 21:29
Thanks, @tylerbecks. I think this is a duplicate of https://github.com/ember-template-lint/ember-template-lint/issues/2010. Closing in lieu of the other issue! Feel free to re-open if I'm wrong.

**Closed by scalvert** 2021-08-30 21:29 UTC
