### ISSUE TITLE
no-duplicate-landmark-elements ignores conditions

### ISSUE THREAD

**Issue by thiagofesta** [ember-template-lint/ember-template-lint#2050] opened 2021-08-04 17:20 UTC
If a template is wrapped with an `if` statement, this rule still throws when it shouldn't.

Example:
```
{{#if this.showFullFooter}}
  <footer>Full Footer</footer>
{{else}}
  <footer>Compact Footer</footer>
{{/if}}
```

**Comment by bertdeblock** [comment] 2021-08-04 17:32
Duplicate of https://github.com/ember-template-lint/ember-template-lint/issues/1799.

**Closed** 2021-08-04 17:36 UTC
